[2024-03-25 15:02:09,428] ERROR log_exception() L1745 Exception on /membro_base [GET] - call_trace=c:\puc\sprint-01-bak\env\lib\site-packages\flask\app.py L1745
Traceback (most recent call last):
  File "C:\PUC\sprint-01-bak\app.py", line 95, in obter_membros_base
    membros = busca_membros_base()
  File "C:\PUC\sprint-01-bak\app.py", line 77, in busca_membros_base
    "nome_mae" : busca_nome_por_id(membro.mae),
  File "C:\PUC\sprint-01-bak\app.py", line 41, in busca_nome_por_id
    membro = session.query(Membro).filter(Membro.id == id).first()
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\orm\query.py", line 2728, in first
    return self.limit(1)._iter().first()  # type: ignore
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\orm\query.py", line 2830, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\orm\session.py", line 2312, in execute
    _add_event=_add_event,
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\orm\session.py", line 2181, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\orm\session.py", line 2050, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
  File "<string>", line 2, in _connection_for_bind
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\orm\session.py", line 1144, in _connection_for_bind
    conn = bind.connect()
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\engine\base.py", line 3279, in connect
    return self._connection_cls(self)
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\engine\base.py", line 3303, in raw_connection
    return self.pool.connect()
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\pool\impl.py", line 172, in _do_get
    code="3o7r",
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\puc\sprint-01-bak\env\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\puc\sprint-01-bak\env\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\puc\sprint-01-bak\env\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\puc\sprint-01-bak\env\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\puc\sprint-01-bak\env\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\puc\sprint-01-bak\env\lib\site-packages\flask_openapi3\scaffold.py", line 127, in view_func
    response = func(**func_kwargs)
  File "C:\PUC\sprint-01-bak\app.py", line 101, in obter_membros_base
    membros = busca_membros_base()
  File "C:\PUC\sprint-01-bak\app.py", line 68, in busca_membros_base
    for membro in membros:
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\orm\query.py", line 2813, in __iter__
    result = self._iter()
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\orm\query.py", line 2830, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\orm\session.py", line 2312, in execute
    _add_event=_add_event,
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\orm\session.py", line 2181, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\orm\session.py", line 2050, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
  File "<string>", line 2, in _connection_for_bind
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\orm\session.py", line 1144, in _connection_for_bind
    conn = bind.connect()
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\engine\base.py", line 3279, in connect
    return self._connection_cls(self)
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\engine\base.py", line 3303, in raw_connection
    return self.pool.connect()
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
  File "c:\puc\sprint-01-bak\env\lib\site-packages\sqlalchemy\pool\impl.py", line 172, in _do_get
    code="3o7r",
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)
[2024-03-25 15:02:09,458] INFO _log() L224  127.0.0.1 - - [25/Mar/2024 15:02:09] "[35m[1mGET /membro_base HTTP/1.1[0m" 500 - - call_trace=c:\puc\sprint-01-bak\env\lib\site-packages\werkzeug\_internal.py L224 
[2024-03-25 15:02:47,381] INFO _log() L224  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.81.234.202:5000 - call_trace=c:\puc\sprint-01-bak\env\lib\site-packages\werkzeug\_internal.py L224 
[2024-03-25 15:02:47,381] INFO _log() L224  [33mPress CTRL+C to quit[0m - call_trace=c:\puc\sprint-01-bak\env\lib\site-packages\werkzeug\_internal.py L224 
[2024-03-25 15:07:58,959] INFO _log() L224  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.81.234.202:5000 - call_trace=c:\puc\sprint-01-bak\env\lib\site-packages\werkzeug\_internal.py L224 
[2024-03-25 15:07:58,959] INFO _log() L224  [33mPress CTRL+C to quit[0m - call_trace=c:\puc\sprint-01-bak\env\lib\site-packages\werkzeug\_internal.py L224 
[2024-03-25 15:08:32,681] INFO _log() L224  127.0.0.1 - - [25/Mar/2024 15:08:32] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=c:\puc\sprint-01-bak\env\lib\site-packages\werkzeug\_internal.py L224 
[2024-03-25 15:08:32,697] INFO _log() L224  127.0.0.1 - - [25/Mar/2024 15:08:32] "GET /openapi/ HTTP/1.1" 200 - - call_trace=c:\puc\sprint-01-bak\env\lib\site-packages\werkzeug\_internal.py L224 
[2024-03-25 15:08:32,713] INFO _log() L224  127.0.0.1 - - [25/Mar/2024 15:08:32] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=c:\puc\sprint-01-bak\env\lib\site-packages\werkzeug\_internal.py L224 
[2024-03-25 15:08:32,713] INFO _log() L224  127.0.0.1 - - [25/Mar/2024 15:08:32] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=c:\puc\sprint-01-bak\env\lib\site-packages\werkzeug\_internal.py L224 
[2024-03-25 15:08:32,716] INFO _log() L224  127.0.0.1 - - [25/Mar/2024 15:08:32] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=c:\puc\sprint-01-bak\env\lib\site-packages\werkzeug\_internal.py L224 
[2024-03-25 15:09:04,471] INFO _log() L224  127.0.0.1 - - [25/Mar/2024 15:09:04] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=c:\puc\sprint-01-bak\env\lib\site-packages\werkzeug\_internal.py L224 
[2024-03-25 15:09:04,513] INFO _log() L224  127.0.0.1 - - [25/Mar/2024 15:09:04] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=c:\puc\sprint-01-bak\env\lib\site-packages\werkzeug\_internal.py L224 
[2024-03-25 15:09:04,513] INFO _log() L224  127.0.0.1 - - [25/Mar/2024 15:09:04] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=c:\puc\sprint-01-bak\env\lib\site-packages\werkzeug\_internal.py L224 
[2024-03-25 15:09:04,514] INFO _log() L224  127.0.0.1 - - [25/Mar/2024 15:09:04] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=c:\puc\sprint-01-bak\env\lib\site-packages\werkzeug\_internal.py L224 
[2024-03-25 15:09:04,696] INFO _log() L224  127.0.0.1 - - [25/Mar/2024 15:09:04] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=c:\puc\sprint-01-bak\env\lib\site-packages\werkzeug\_internal.py L224 
